In [ ]:
!pip install kaggle

In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [ ]:
!kaggle datasets download -d omkargurav/face-mask-dataset

In [ ]:
from zipfile import ZipFile
dataset = '/content/face-mask-dataset.zip'

with ZipFile(dataset,'r') as zip:
  zip.extractall()
  print('The dataset is extracted')

In [ ]:
!ls


data  face-mask-dataset.zip  kaggle.json  sample_data


In [ ]:
import os
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import cv2
from google.colab.patches import cv2_imshow
from PIL import Image 
from sklearn.model_selection import train_test_split

In [ ]:
with_mask_files = os.listdir('path of the with mask image folder ')
print(with_mask_files[0:5])
print(with_mask_files[-5:])

['with_mask_1451.jpg', 'with_mask_1854.jpg', 'with_mask_3117.jpg', 'with_mask_764.jpg', 'with_mask_2552.jpg']
['with_mask_523.jpg', 'with_mask_1575.jpg', 'with_mask_1161.jpg', 'with_mask_1199.jpg', 'with_mask_732.jpg']


In [ ]:
without_mask_files = os.listdir('path of the without mask image folder ')
print(without_mask_files[0:5])
print(without_mask_files[-5:])

['without_mask_1943.jpg', 'without_mask_1766.jpg', 'without_mask_29.jpg', 'without_mask_1023.jpg', 'without_mask_2036.jpg']
['without_mask_3796.jpg', 'without_mask_1154.jpg', 'without_mask_706.jpg', 'without_mask_173.jpg', 'without_mask_1009.jpg']


In [ ]:
print('Number of with mask images:', len(with_mask_files))
print('Number of without mask images:', len(without_mask_files))

Number of with mask images: 3725
Number of without mask images: 3828


In [ ]:

with_mask_labels = [1]*3725

without_mask_labels = [0]*3828

In [ ]:
print(with_mask_labels[0:5])

print(without_mask_labels[0:5])

[1, 1, 1, 1, 1]
[0, 0, 0, 0, 0]


In [ ]:
print(len(with_mask_labels))
print(len(without_mask_labels))

3725
3828


In [ ]:
labels = with_mask_labels + without_mask_labels

In [ ]:
print(len(labels))
print(labels[0:5])
print(labels[-5:])

7553
[1, 1, 1, 1, 1]
[0, 0, 0, 0, 0]


In [ ]:
# convert images to numpy arrays+

with_mask_path = 'path of the with mask image folder '

data = []

for img_file in with_mask_files:

  image = Image.open(with_mask_path + img_file)
  image = image.resize((128,128))
  image = image.convert('RGB')
  image = np.array(image)
  data.append(image)

/usr/local/lib/python3.10/dist-packages/PIL/Image.py:975: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(


In [ ]:
without_mask_path = 'path of the without mask image folder'


for img_file in without_mask_files:

  image = Image.open(without_mask_path + img_file)
  image = image.resize((128,128))
  image = image.convert('RGB')
  image = np.array(image)
  data.append(image)

In [ ]:

len(data)

7553

In [ ]:
data[0]

array([[[118, 122, 125],
        [119, 123, 126],
        [119, 123, 126],
        ...,
        [140, 150, 152],
        [140, 150, 152],
        [139, 149, 151]],

       [[118, 122, 125],
        [118, 122, 125],
        [118, 122, 125],
        ...,
        [140, 150, 152],
        [140, 150, 152],
        [139, 149, 151]],

       [[118, 122, 125],
        [118, 122, 125],
        [118, 122, 125],
        ...,
        [140, 150, 152],
        [140, 150, 152],
        [139, 149, 151]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [ ]:
type(data[0])

numpy.ndarray

In [ ]:
data[0].shape

(128, 128, 3)

In [ ]:
# converting image list and label list to numpy arrays

X = np.array(data)
Y = np.array(labels)

In [ ]:
type(X)

numpy.ndarray

In [ ]:
type(Y)

numpy.ndarray

In [ ]:
print(X.shape)
print(Y.shape)

(7553, 128, 128, 3)
(7553,)


In [ ]:
print(Y)

[1 1 1 ... 0 0 0]


In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2)

In [ ]:
print(X.shape, X_train.shape, X_test.shape)

(7553, 128, 128, 3) (6042, 128, 128, 3) (1511, 128, 128, 3)


In [ ]:
X_train_scaled = X_train/255

X_test_scaled = X_test/255

In [ ]:
X_train[0]

array([[[120,  90,  69],
        [103,  72,  50],
        [107,  76,  54],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[114,  84,  60],
        [103,  73,  49],
        [110,  79,  56],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[115,  85,  61],
        [110,  80,  56],
        [110,  79,  56],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[253, 253, 253],
        [254, 254, 254],
        [255, 255, 255],
        ...,
        [ 27,  35,  60],
        [ 25,  33,  70],
        [ 24,  33,  66]],

       [[253, 253, 253],
        [254, 254, 254],
        [255, 255, 255],
        ...,
        [ 27,  35,  61],
        [ 25,  33,  70],
        [ 24,  33,  66]],

       [[253, 253, 253],
        [254, 254, 254],
        [255, 255, 255],
        ...,
        [ 27,  35,  61],
        [ 25,  33,  70],
        [ 24,  33,  66]]

In [ ]:
X_train_scaled[0]

array([[[0.47058824, 0.35294118, 0.27058824],
        [0.40392157, 0.28235294, 0.19607843],
        [0.41960784, 0.29803922, 0.21176471],
        ...,
        [1.        , 1.        , 1.        ],
        [1.        , 1.        , 1.        ],
        [1.        , 1.        , 1.        ]],

       [[0.44705882, 0.32941176, 0.23529412],
        [0.40392157, 0.28627451, 0.19215686],
        [0.43137255, 0.30980392, 0.21960784],
        ...,
        [1.        , 1.        , 1.        ],
        [1.        , 1.        , 1.        ],
        [1.        , 1.        , 1.        ]],

       [[0.45098039, 0.33333333, 0.23921569],
        [0.43137255, 0.31372549, 0.21960784],
        [0.43137255, 0.30980392, 0.21960784],
        ...,
        [1.        , 1.        , 1.        ],
        [1.        , 1.        , 1.        ],
        [1.        , 1.        , 1.        ]],

       ...,

       [[0.99215686, 0.99215686, 0.99215686],
        [0.99607843, 0.99607843, 0.99607843],
        [1.        , 1

In [ ]:
import tensorflow as tf
from tensorflow import keras

In [ ]:
num_of_classes = 2

model = keras.Sequential()

model.add(keras.layers.Conv2D(32, kernel_size=(3,3), activation='relu', input_shape=(128,128,3)))
model.add(keras.layers.MaxPooling2D(pool_size=(2,2)))


model.add(keras.layers.Conv2D(64, kernel_size=(3,3), activation='relu'))
model.add(keras.layers.MaxPooling2D(pool_size=(2,2)))

model.add(keras.layers.Flatten())

model.add(keras.layers.Dense(128, activation='relu'))
model.add(keras.layers.Dropout(0.5))

model.add(keras.layers.Dense(64, activation='relu'))
model.add(keras.layers.Dropout(0.5))


model.add(keras.layers.Dense(num_of_classes, activation='sigmoid'))

In [ ]:
# compile the neural network
model.compile(optimizer='rcParams',
              loss='sparse_categorical_crossentropy',
              metrics=['acc'])

In [ ]:
# training the neural network
history = model.fit(X_train_scaled, Y_train, validation_split=0.1, epochs=5)

Epoch 1/5
170/170 [==============================] - 15s 22ms/step - loss: 0.4588 - acc: 0.8030 - val_loss: 0.3025 - val_acc: 0.8727
Epoch 2/5
170/170 [==============================] - 3s 19ms/step - loss: 0.2824 - acc: 0.8939 - val_loss: 0.2280 - val_acc: 0.9025
Epoch 3/5
170/170 [==============================] - 3s 18ms/step - loss: 0.2393 - acc: 0.9099 - val_loss: 0.2302 - val_acc: 0.9025
Epoch 4/5
170/170 [==============================] - 3s 17ms/step - loss: 0.1912 - acc: 0.9319 - val_loss: 0.2628 - val_acc: 0.8876
Epoch 5/5
170/170 [==============================] - 3s 17ms/step - loss: 0.1500 - acc: 0.9456 - val_loss: 0.2798 - val_acc: 0.8959


In [ ]:
model.summary()

In [ ]:
model.save('face_mask_detection.h5')

In [ ]:
loss, accuracy = model.evaluate(X_test_scaled, Y_test)
print('Test Accuracy =', accuracy)

In [ ]:
h = history

plt.plot(h.history['loss'], label='train loss')
plt.plot(h.history['val_loss'], label='validation loss')
plt.legend()
plt.show()

plt.plot(h.history['acc'], label='train accuracy')
plt.plot(h.history['val_acc'], label='validation accuracy')
plt.legend()
plt.show()

In [ ]:
model = tf.keras.models.load_model('face_mask_detection.h5')

img_width, img_height = 150, 150

labels = {0: 'with_mask', 1: 'without_mask'}

# Define the function to make predictions on new images

def detect_face_mask(image):
    # Convert the image to the appropriate format and resize it
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    image = cv2.resize(image, (img_width, img_height))

    # Expand the dimensions of the image
    image = np.expand_dims(image, axis=0)

    # Make a prediction on the image
    prediction = model.predict(image)

    # Get the index of the predicted label
    predicted_label_index = int(np.round(prediction[0][0]))

    # Get the label of the prediction
    predicted_label = labels[predicted_label_index]

    return predicted_label

# Test the function on a sample image
image_path = 'path/to/test/image'
image = cv2.imread(image_path)
predicted_label = detect_face_mask(image)

print('The predicted label for the image is:', predicted_label)